# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-18 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geonames', '0002_fixtures'),
    ]

    operations = [
        migrations.CreateModel(
            name='NationalIdentificationCodeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('input_mask', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geonames.Country')),
            ],
        ),
        migrations.CreateModel(
            name='PostalAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=45, verbose_name='PostalAddress line 1')),
                ('address_line2', models.CharField(blank=True, max_length=45, verbose_name='PostalAddress line 2')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Postal Code')),
                ('state_province', models.CharField(blank=True, max_length=40, verbose_name='State/Province')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geonames.GeonamesAdm3')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geonames.Country')),
            ],
        ),
    ]
