# Generated by Django 3.2.10 on 2022-04-21 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geonames_address', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationalidentificationcodetype',
            name='acronym',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='nationalidentificationcodetype',
            name='default',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='address_line1',
            field=models.CharField(max_length=200, verbose_name='PostalAddress line 1'),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='address_line2',
            field=models.CharField(blank=True, max_length=200, verbose_name='PostalAddress line 2'),
        ),
        migrations.CreateModel(
            name='NationalIdentificationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nic', models.CharField(db_index=True, max_length=200, verbose_name='National Identification Code')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geonames_address.nationalidentificationcodetype')),
            ],
        ),
    ]
